name: Deployment2

on: 
  workflow_dispatch:
   inputs:
      VersionNumber:
        description: 'The New Version Number Ex: "1.2.3"'
        required: true
        type: string
        default: "0.0.0"

      IsPreRelease:
        description: 'Is Prelease'
        required: true
        type: boolean
        default: true

      Changelog:
        description: 'The Main Change Log'
        required: true
        type: string
        default: 'added: fixed: removed:'



jobs:
  build-Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
