name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  msbuild-windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Premake install
      run: ./premake.bat install

    - name: Run Premake
      run: ./VS_2022.bat

    - name: Build 64 bit
      run: ./premake.bat buildeditor

    - name: Build 32 bit
      run: ./premake.bat buildeditor32

    - name: Run Tests 64 bit
      run: ./premake.bat test

    - name: Run Tests 32 bit
      run: ./premake.bat test32
  
  gmake-linux-build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Make a scripts executable
      run: |
       chmod +x ./GNU_Make.sh
       chmod +x ./premake.sh

    - name: Run Premake install
      run: ./premake.sh install

    - name: Run Premake
      run: ./GNU_Make.sh
    
    - name: Build 64 bit
      run: ./premake.sh buildeditor

    - name: RunTests for 64 bit
      run: ./premake.sh test

  clang-macos-build:
    runs-on: macos-latest
    if: false # build takes over 30 mins 
         
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Make a scripts executable
      run: |
       chmod +x ./GNU_Make.sh
       chmod +x ./premake.sh

    - name: Run Premake install
      run: ./premake.sh install

    - name: Run Premake
      run: ./GNU_Make.sh
    
    - name: Build 64 bit
      run: ./premake.sh buildeditor

    - name: RunTests for 64 bit
      run: ./premake.sh test

  gmake-wasm-build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Make a scripts executable
      run: |
       chmod +x ./GNU_Make.sh

    - name: Run Premake Install
      uses: mymindstorm/setup-emsdk@v13

    - name: Run Premake
      run: ./GNU_Make.sh
    
    - name: Build Wasm Debug
      run: ./premake.sh web_build

    - name: Build Wasm Pub
      run: ./premake.sh buildwasmpub
      
  clang-android-build:
    runs-on: ubuntu-latest 
    if: 'false'

    steps:
      - name: TODO
        run: echo "TODO"

  clang-ios-build:
    runs-on: ubuntu-latest 
    if: 'false'

    steps:
      - name: TODO
        run: echo "TODO"