name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  msbuild-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Premake install
      run: ./premake.sh install

    - name: Run Premake
      run: VS_2022.bat

    - name: Restore cached objs
      id: cache-objs-restore
      uses: actions/cache/restore@v3
      with:
        path: ./Output
        key: ${{ runner.os }}-1

    - name: Build 64 bit
      run: ./premake.bat buildeditor

    - name: Build 32 bit
      run: ./premake.bat buildeditor32

    - name: Save cached Objs
      id: cache-Objs-save
      uses: actions/cache/save@v3
      with:
        path: ./Output
        key: ${{ steps.cache-objs-restore.outputs.cache-primary-key }}


    - name: Run Tests 64 bit
      run: ./premake.bat test

    - name: Run Tests 32 bit
      run: ./premake.bat test32
  
  gmake-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make a scripts executable
      run: |
       chmod +x ./GNU_Make.sh
       chmod +x ./premake.sh

    - name: Run Premake install
      run: ./premake.sh install

    - name: Run Premake
      run: ./GNU_Make.sh
    
    - name: Restore cached objs
      id: cache-objs-restore
      uses: actions/cache/restore@v3
      with:
        path: ./Output
        key: ${{ runner.os }}-1

    - name: Build 64 bit
      run: ./premake.sh buildeditor

    - name: Save cached Objs
      id: cache-Objs-save
      uses: actions/cache/save@v3
      with:
        path: ./Output
        key: ${{ steps.cache-objs-restore.outputs.cache-primary-key }}

    - name: RunTests for 64 bit
      run: ./premake.sh test

  clang-build:
    runs-on: ubuntu-latest  
    if: 'false'
    
    steps:
      - name: TODO
        run: echo "TODO"

  web-build:
    runs-on: ubuntu-latest 
    if: 'false'

    steps:
      - name: TODO
        run: echo "TODO"

  android-build:
    runs-on: ubuntu-latest 
    if: 'false'

    steps:
      - name: TODO
        run: echo "TODO"

  ios-build:
    runs-on: ubuntu-latest 
    if: 'false'

    steps:
      - name: TODO
        run: echo "TODO"