name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  msbuild-windows-64bit-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"

    - name: Run Premake install dependencies
      run: premake5 installdependencies

    - name: Run Premake
      run: premake5 vs2022

    - name: Build
      run: premake5 buildeditor

    - name: Run Tests
      run: premake5 test

  
  msbuild-windows-32bit-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake install
      run: premake5 installdependencies

    - name: Run Premake
      run: premake5 vs2022

    - name: Build bit
      run: premake5 buildeditor32

    - name: Run Tests
      run: premake5 test32


  gmake-linux-bit64-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake install
      run: premake5 installdependencies

    - name: Run Premake
      run: premake5 gmake2
    
    - name: Build
      run: premake5 buildeditor

    - name: Run Tests
      run: premake5 test

  gmake-linux-bit32-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add gcc multilib to PATH
      run: sudo apt install gcc-multilib g++-multilib

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake install
      run: premake5 install

    - name: Run Premake
      run: premake5 gmake2

    - name: Build
      run: premake5 buildeditor32

    - name: Run Tests 
      run: premake5 test32

  clang-macos-build:
    runs-on: macos-latest
    if: false # build takes over 30 mins 
         
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake install
      run: premake5 install

    - name: Run Premake
      run: premake5 gmake2
    
    - name: Build
      run: premake5 buildeditor

    - name: Run Tests
      run: premake5 test

  gmake-wasm-build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add Premake to PATH
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"      

    - name: Run Premake Install
      uses: mymindstorm/setup-emsdk@v13

    - name: Run Premake
      run:  premake5 gmake2
    
    - name: Build
      run:  premake5 buildwasm

    - name: Build Wasm Pub
      run:  premake5 buildwasmpub
      
  clang-android-build:
    runs-on: ubuntu-latest 
    if: 'false'

    steps:
      - name: TODO
        run: echo "TODO"

  clang-ios-build:
    runs-on: ubuntu-latest 
    if: 'false'

    steps:
      - name: TODO
        run: echo "TODO"
